In [6]:
import numpy as np
import pandas as pd

# Series를 생성해 보아요!
s = pd.Series([-1, 5, 10, 99],
              dtype=np.float64)
print(s)
print(s.values) # [-1.  5. 10. 99.]
print(s.index) # RangeIndex(start=0, stop=4, step=1)
print(s.dtype) # float64

0    -1.0
1     5.0
2    10.0
3    99.0
dtype: float64
[-1.  5. 10. 99.]
RangeIndex(start=0, stop=4, step=1)
float64

In [9]:
# Series는 생성할 때 index를 지정할 수 있어요!
# 지정인덱스를 사용할 수 있어요!
s = pd.Series([-1, 10, -8, 20],
              dtype=np.float64,
              index=['c', 'b', 'a', 'kkk'])
print(s)
print(s[1]) # 숫자 index를 이용해서 indexing => 10
print(s['a']) # -8

c    -1.0
b    10.0
a    -8.0
k    20.0
dtype: float64
10.0
-8.0

<ipython-input-9-8d44daddab36>:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1]) # 숫자 index를 이용해서 indexing => 10

In [13]:
# Series를 생성할 때 지정 index를 사용해서 Series를
# 생성할 꺼예요!
s = pd.Series([-1, 10, -8, 20],
              dtype=np.float64,
              index=[0, 2, 100, 6])
print(s)
print(s[2]) # 10 아하...지정index가 우선이군요!
# print(s[3]) # key error

0      -1.0
2      10.0
100    -8.0
6      20.0
dtype: float64
10.0

KeyError: 3

In [17]:
# Series를 생성할 때 지정 index를 사용해서 Series를
# 생성할 꺼예요!
# 같은 index를 사용할 수 있어요!
s = pd.Series([-1, 10, -8, 20],
              dtype=np.float64,
              index=['c', 'a', 'k', 'a'])
print(s)
print(s['a'])

c    -1.0
a    10.0
k    -8.0
a    20.0
dtype: float64
a    10.0
a    20.0
dtype: float64

In [23]:
# Series에서 slicing은 어떻게 되나요?
s = pd.Series([-1, 10, -8, 20],
              dtype=np.float64,
              index=['c', 'a', 'k', 'b'])
print(s)
# print(s[0:2])
new_s = s[0:2]
# print(new_s)
new_s[0] = 100
print(new_s)
print(s)

c    -1.0
a    10.0
k    -8.0
b    20.0
dtype: float64
c    100.0
a     10.0
dtype: float64
c    100.0
a     10.0
k     -8.0
b     20.0
dtype: float64

<ipython-input-23-7313db82cf43>:9: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  new_s[0] = 100

In [24]:
# Series에서 slicing은 어떻게 되나요?
s = pd.Series([-1, 10, -8, 20],
              dtype=np.float64,
              index=['c', 'a', 'k', 'b'])
print(s)
print(s['a':'b'])

c    -1.0
a    10.0
k    -8.0
b    20.0
dtype: float64
a    10.0
k    -8.0
b    20.0
dtype: float64

In [27]:
# Series에서 Fancy indexing할 수 있나요? => 가능
# Series에서 Boolean indexing을 할 수 있나요? => 가능
# Series도 Numpy의 ndarray에서 했던것처럼 집계함수가 있나요? => 네!
s = pd.Series([-1, 10, -8, 20],
              dtype=np.float64,
              index=['c', 'a', 'k', 'b'])
print(s[[0,2]])
# 현재 Series에서 -5보다 큰 값만 추출하세요!(Series형태로)
print(s[s > -5])
print(s.sum()) # 21.0

c   -1.0
k   -8.0
dtype: float64
c    -1.0
a    10.0
b    20.0
dtype: float64
21.0

<ipython-input-27-38ef566a5248>:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[0,2]])

In [30]:
# dictionary를 이용해서 Series를 만들어보아요!
import numpy as np
import pandas as pd

my_dict = {
    "서울": 3000,
    "인천": 2000,
    "제주": 1000
}

s = pd.Series(my_dict)
print(s)
print(s[0]) # 3000
print(s['제주']) # 1000

서울    3000
인천    2000
제주    1000
dtype: int64
3000
1000

<ipython-input-30-11c6aad97b22>:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0]) # 3000

In [33]:
# Series에 요소를 추가하거나 삭제하려면 어떻게 해야 하나요?
s = pd.Series([1,2,3,4])
print(s)
s[4] = 5
print(s)
# 값을 삭제할 경우에는 drop을 이용해요!
s = s.drop(2)
print(s)

0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
3    4
4    5
dtype: int64

In [37]:
# A공장이 있어요!
# 2020-01-01부터 10일간의 생산량을 Series로 저장할꺼예요!
# 생산량은 평균이 50이고 표준편차가 5인 정규분포에서 랜덤하게 추출(정수)

# B공장이 있어요!
# 2020-01-05부터 10일간의 생산량을 Series로 저장할꺼예요!
# 생산량은 평균이 70이고 표준편차가 8인 정규분포에서 랜덤하게 추출(정수)

# 날짜별로 생산량의 합을 구할꺼예요!

import numpy as np
import pandas as pd
from datetime import date, datetime, timedelta
from dateutil.parser import parse

start_day = datetime(2020,1,1) # 2020-01-01 날짜에 대한 날짜값.
# 10일간의 생산량을 랜덤하게 생성해서 list를 만들어보아요!
a_factory_amount = [int(x) for x in np.random.normal(50,5,(10,))]
a_factory_index = [start_day + timedelta(days=x) for x in range(10)]
a_factory_s = pd.Series(a_factory_amount,
                        index=a_factory_index)
print(a_factory_s)

start_day = datetime(2020,1,5) # 2020-01-05 날짜에 대한 날짜값.
# 10일간의 생산량을 랜덤하게 생성해서 list를 만들어보아요!
b_factory_amount = [int(x) for x in np.random.normal(70,8,(10,))]
b_factory_index = [start_day + timedelta(days=x) for x in range(10)]
b_factory_s = pd.Series(b_factory_amount,
                        index=b_factory_index)
print(b_factory_s)

# 전체 생산량을 알기 위해서 두 공장의 생산량을 날짜별로
# 더해줄꺼예요!
print(a_factory_s + b_factory_s)

2020-01-01    44
2020-01-02    48
2020-01-03    44
2020-01-04    45
2020-01-05    42
2020-01-06    54
2020-01-07    51
2020-01-08    56
2020-01-09    48
2020-01-10    54
dtype: int64
2020-01-05    78
2020-01-06    64
2020-01-07    71
2020-01-08    81
2020-01-09    58
2020-01-10    72
2020-01-11    85
2020-01-12    65
2020-01-13    64
2020-01-14    63
dtype: int64
2020-01-01      NaN
2020-01-02      NaN
2020-01-03      NaN
2020-01-04      NaN
2020-01-05    120.0
2020-01-06    118.0
2020-01-07    122.0
2020-01-08    137.0
2020-01-09    106.0
2020-01-10    126.0
2020-01-11      NaN
2020-01-12      NaN
2020-01-13      NaN
2020-01-14      NaN
dtype: float64

In [41]:
# 이 문제를 해결해보세요!
# A 공장의 1월 11일~14일까지 지정인덱스를 추가하고 생산량을 0으로 설정
# B 공장의 1월 1일~4일까지 지정인덱스를 추가하고 생산량을 0으로 설정

index_a = set(a_factory_index)
print(index_a)
index_b = set(b_factory_index)
print(index_b)

index_a_b = index_a - index_b  # 1월1일 ~ 4일까지의 값이 남아요!
index_b_a = index_b - index_a  # 1월 11일 ~ 14일까지의 값이 남아요!

for i in index_a_b:
    b_factory_s[i] = 0

for i in index_b_a:
    a_factory_s[i] = 0

print(a_factory_s + b_factory_s)

{datetime.datetime(2020, 1, 8, 0, 0), datetime.datetime(2020, 1, 5, 0, 0), datetime.datetime(2020, 1, 9, 0, 0), datetime.datetime(2020, 1, 3, 0, 0), datetime.datetime(2020, 1, 6, 0, 0), datetime.datetime(2020, 1, 4, 0, 0), datetime.datetime(2020, 1, 7, 0, 0), datetime.datetime(2020, 1, 10, 0, 0), datetime.datetime(2020, 1, 2, 0, 0), datetime.datetime(2020, 1, 1, 0, 0)}
{datetime.datetime(2020, 1, 8, 0, 0), datetime.datetime(2020, 1, 12, 0, 0), datetime.datetime(2020, 1, 5, 0, 0), datetime.datetime(2020, 1, 14, 0, 0), datetime.datetime(2020, 1, 9, 0, 0), datetime.datetime(2020, 1, 6, 0, 0), datetime.datetime(2020, 1, 11, 0, 0), datetime.datetime(2020, 1, 7, 0, 0), datetime.datetime(2020, 1, 10, 0, 0), datetime.datetime(2020, 1, 13, 0, 0)}
2020-01-01     44
2020-01-02     48
2020-01-03     44
2020-01-04     45
2020-01-05    120
2020-01-06    118
2020-01-07    122
2020-01-08    137
2020-01-09    106
2020-01-10    126
2020-01-11     85
2020-01-12     65
2020-01-13     64
2020-01-14     63
Freq: D, dtype: int64

In [48]:
# DataFrame에 대해서 알아보아요!

# 먼저 DataFrame을 생성해보아요 => dictionary로 생성.

import numpy as np
import pandas as pd

data = {
    'name': ['홍길동','신사임당','강감찬', '이순신'],
    'year': [2020, 2021, 2020, 2023],
    'grade': [3.1, 4.0, 1.2, 2.5]
}
# Series를 만들때는 key값이 지정 index로 사용.
# DataFrame을 만들때는 key값이 컬럼명으로 사용.

# s = pd.Series(data)
df = pd.DataFrame(data)
display(df)

# 기억해야 하는 속성(기본속성)
print(df.shape) # (4, 3) => 총 데이터 12개
print(df.size) # 12
print(df.ndim) # 2
print(df.values)

   name  year  grade
0   홍길동  2020    3.1
1  신사임당  2021    4.0
2   강감찬  2020    1.2
3   이순신  2023    2.5

(4, 3)
12
2
[['홍길동' 2020 3.1]
 ['신사임당' 2021 4.0]
 ['강감찬' 2020 1.2]
 ['이순신' 2023 2.5]]

In [55]:
# DataFrame의 index, column, values

import numpy as np
import pandas as pd

data = {
    'name': ['홍길동','신사임당','강감찬', '이순신'],
    'year': [2020, 2021, 2020, 2023],
    'grade': [3.1, 4.0, 1.2, 2.5]
}

df = pd.DataFrame(data)
display(df)

print(df.index)  # RangeIndex(start=0, stop=4, step=1)
print(df.values) # 2차원 ndarray로 데이터만 추출
print(df.columns) # Index(['name', 'year', 'grade'], dtype='object')
print(df.columns[0]) # name

   name  year  grade
0   홍길동  2020    3.1
1  신사임당  2021    4.0
2   강감찬  2020    1.2
3   이순신  2023    2.5

RangeIndex(start=0, stop=4, step=1)
[['홍길동' 2020 3.1]
 ['신사임당' 2021 4.0]
 ['강감찬' 2020 1.2]
 ['이순신' 2023 2.5]]
Index(['name', 'year', 'grade'], dtype='object')
name

In [57]:
# DataFrame을 생성한 후
# index와 컬럼명을 변경하고 싶어요!
data = {
    'name': ['홍길동','신사임당','강감찬', '이순신'],
    'year': [2020, 2021, 2020, 2023],
    'grade': [3.1, 4.0, 1.2, 2.5]
}

df = pd.DataFrame(data)
display(df)

new_df = df.rename(columns={'year':'입학연도',
                            'grade': '성적'},
                   index={0: 'zero'},
                   inplace=False)
display(new_df)

   name  year  grade
0   홍길동  2020    3.1
1  신사임당  2021    4.0
2   강감찬  2020    1.2
3   이순신  2023    2.5

      name  입학연도   성적
zero   홍길동  2020  3.1
1     신사임당  2021  4.0
2      강감찬  2020  1.2
3      이순신  2023  2.5

In [59]:
# 특정 column을 index로 사용할 수 있어요!
data = {
    'name': ['홍길동','신사임당','강감찬', '이순신'],
    'year': [2020, 2021, 2020, 2023],
    'grade': [3.1, 4.0, 1.2, 2.5]
}

df = pd.DataFrame(data)
display(df)

new_df = df.set_index('name',
                       inplace=False)
display(new_df)

   name  year  grade
0   홍길동  2020    3.1
1  신사임당  2021    4.0
2   강감찬  2020    1.2
3   이순신  2023    2.5

      year  grade
name
홍길동   2020    3.1
신사임당  2021    4.0
강감찬   2020    1.2
이순신   2023    2.5

In [60]:
# 행과 열의 위치를 바꿀 수 있어요!~
data = {
    'name': ['홍길동','신사임당','강감찬', '이순신'],
    'year': [2020, 2021, 2020, 2023],
    'grade': [3.1, 4.0, 1.2, 2.5]
}

df = pd.DataFrame(data)
display(df)

new_df = df.transpose()
display(new_df)

   name  year  grade
0   홍길동  2020    3.1
1  신사임당  2021    4.0
2   강감찬  2020    1.2
3   이순신  2023    2.5

          0     1     2     3
name    홍길동  신사임당   강감찬   이순신
year   2020  2021  2020  2023
grade   3.1   4.0   1.2   2.5

In [ ]:
# 일반적으로 우리가 사용하는 데이터 파일의 형식
# 1. CSV파일 (.csv)
#    naive한 형태의 데이터 파일형식
#    Comma Seperated Value(콤마로 나뉘어진 값)
#    예)
#    홍길동,20,서울,김길동,30,부산,최길동,50,인천,...
#    장점 : 부가적인 데이터가 적게 들어가요!
#           상대적으로 사이즈가 큰 데이터를 표현하기에 적합해요!
#    단점 : 데이터를 해석하거나 사용하는데 어려움이 따라요!
#           유지보수가 어려워요!
# 2. xml파일( .xml)
#    Extended Markup Language
#    예)
#     <person>
#        <name>홍길동</name><age>20</age><address>서울</address>
#     <person>
#     <person>
#        <name>김길동</name><age>30</age><address>부산</address>
#     <person>
#     장점은 사용하기가 아주 쉬워요. 데이터 표현을 쉽게 할 수 있어요!
#     단점은 사이즈가 너무 커져요!
# 3. JSON
#    JavaScript Object Notation(자바스크립트 객체 표현법)
#    예) {person : {name : '홍길동', age:20, address:'서울'}}

In [66]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/KDTHome/[data]/movies.csv')

# display(df)

# display(df.head(10)) # head()는 DataFrame의 시작 부터 x개의 행을 가져오는 함수
                   # 인자가 없으면 기본값으로 5를 설정.
# display(df.tail())
print(df.shape)  # (9742, 3)

(9742, 3)

In [67]:
# 파일(CSV)로부터 데이터를 읽어와서 쉽게 DatraFrame을 생성할 수
# 있어요!
# 이번에는 Open API를 이용해서 데이터를 JSON형태로 가져와서
# 그걸 이용해 DataFrame을 생성해 볼꺼예요!
# 1. Open API는 어떤것을 사용할 껀가요?
#    영화진흥위원회 Open API를 사용해 보아요!
#    일별 box office 순위를 알려주는 Open API를 이용해서
#    JSON데이터를 받아올 꺼예요!

# 내일 여기부터 다시 시작해요!