In [9]:
# DataFrame에서 중복을 처리하려면 어떻게 해야 하나요?
# 일반적으로 중복데이터인 경우에는 삭제하는게 보통!
# 특이한 경우 중복데이터를 그냥 사용하는 경우도 있는데 말 그대로
# 특이한 case이고 일반적이지 않아요!

import numpy as np
import pandas as pd

data = {
    'c1' : ['a', 'a', 'b', 'a', 'c'],
    'c2' : [1,1,1,2,3],
    'c3' : [1,1,2,2,2]
}
df = pd.DataFrame(data)
display(df)
# new_df = df.duplicated()
# display(new_df)  # Boolean mask를 생성할 수 있어요!

# 이 duplicated()함수를 Series에도 적용할 수 있어요!
# my_col = df['c2'].duplicated()
# print(my_col)

# 중복데이터를 그냥 제거해주는 함수도 있어요!
# new_df = df.drop_duplicates() # 모든 컬럼에 대해서 중복을 확인
new_df = df.drop_duplicates(subset=['c2','c3'])
display(new_df)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  c   3   2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  c   3   2

In [29]:
# Binning 처리(구간분할 처리)
# MPG Data set을 예로 처리해 보아요!

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/KDTHome/[data]/auto-mpg.csv',
                 header=None)
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleratioin', 'model_year', 'origin', 'name']
# display(df)
# df.info()
# print(df['horsepower'].value_counts())
# 해당 Series에 숫자가 아닌 값이 있는지 확인해 보아요!
# 현재 데이터 타입이 object로 되어 있어서 정규식을 이용해서 처리해야할듯
# 보여요!

# 사실 horsepower에 '?' 문자가 들어가 있어요!
# horserpower를 알 수 없어서 '?' 문자를 대신 데이터에 넣어놓은건대
# 이건 어떻게 처리해야 하나요?
df['horsepower'].replace('?', np.nan, inplace=True)
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower'] = df['horsepower'].astype('float')

# 이제 이 자동차의 마력(출력)을 Binning처리 해 보아요!
# 저출력, 보통 출력, 고출력의 형태로 Binning처리를 해 보아요!
# 이런 Binning처리할 때 일단 np가 가지고 있는 histogram()을
# 이용하면 편해요. 특정 구간에 데이터가 몇개 있는지 알려줘요!

count, divider =  np.histogram(df['horsepower'], bins=3)
print(count)  # [257 103  32]
print(divider) # [ 46.         107.33333333 168.66666667 230.        ]

bin_name = ['저출력', '보통출력', '고출력']

df['hp_cut'] = pd.cut(x=df['horsepower'],
                      bins=divider,
                      labels=bin_name,
                      include_lowest=True)

# display(df)

# 이렇게 category 데이터 형태로 기존 데이터를 변형 시킬 수 있어요!
# 여기서 하나 더 추가적으로 작업해야 하는 경우가 있어요!
horsepowser_dummies = pd.get_dummies(df['hp_cut'])
display(horsepowser_dummies)

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]

<ipython-input-29-762f6fa57c28>:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].replace('?', np.nan, inplace=True)

       저출력   보통출력    고출력
0    False   True  False
1    False   True  False
2    False   True  False
3    False   True  False
4    False   True  False
..     ...    ...    ...
393   True  False  False
394   True  False  False
395   True  False  False
396   True  False  False
397   True  False  False

[392 rows x 3 columns]

In [32]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/KDTHome/[data]/auto-mpg.csv',
                 header=None)
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleratioin', 'model_year', 'origin', 'name']

df['horsepower'].replace('?', np.nan, inplace=True)
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower'] = df['horsepower'].astype('float')

display(df['horsepower'])
# 해당 컬럼을 min-max scaling을 이용해서 정규화 시킬꺼예요!
max_min = df['horsepower'].max() - df['horsepower'].min()
df['horsepower_norm'] = ((df['horsepower'] - df['horsepower'].min())) / max_min
display(df)

<ipython-input-32-2f54a3bb8eef>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].replace('?', np.nan, inplace=True)

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 392, dtype: float64

,mpg,cylinders,displacement,horsepower,weight,acceleratioin,model_year,origin,name,horsepower_norm
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,0.456522
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,0.646739
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,0.565217
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,0.565217
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,0.510870
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790.0,15.6,82,1,ford mustang gl,0.217391
394,44.0,4,97.0,52.0,2130.0,24.6,82,2,vw pickup,0.032609
395,32.0,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage,0.206522
396,28.0,4,120.0,79.0,2625.0,18.6,82,1,ford ranger,0.179348
397,31.0,4,119.0,82.0,2720.0,19.4,82,1,chevy s-10,0.195652

In [40]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame({
    'a' : ['a0', 'a1', 'a2', 'a3'],
    'b' : [1, 2, 3, 4],
    'c' : ['c0', 'c1', 'c2', 'c3']
}, index=[0, 1, 2, 3])

df2 = pd.DataFrame({
    'b' : ['b0', 'b1', 'b2', 'b3'],
    'c' : ['c0', 'c1', 'c2', 'c3'],
    'd' : ['d0', 'd1', 'd2', 'd3'],
    'e' : ['e0', 'e1', 'e2', 'e3']
}, index=[2, 3, 4, 5])
display(df1, df2)

# 이제 두개의 DataFrame을 연결해보아요!!
# DataFrame 2개를 연결하려해요 그럼 방향이 있어야 해요!
# 위,아래   or 좌,우 ===> axis
# index에 상관없이 그냥 붙어요!. 컬럼명을 기준으로 붙여요!
# 데이터 타입이 다르면 자동으로 변환시켜요!
# result = pd.concat([df1, df2], axis=0)
# result = pd.concat([df1, df2], axis=0,
#                    ignore_index=True)
# display(result)

result = pd.concat([df1, df2], axis=1)
display(result)

    a  b   c
0  a0  1  c0
1  a1  2  c1
2  a2  3  c2
3  a3  4  c3

    b   c   d   e
2  b0  c0  d0  e0
3  b1  c1  d1  e1
4  b2  c2  d2  e2
5  b3  c3  d3  e3

     a    b    c    b    c    d    e
0   a0  1.0   c0  NaN  NaN  NaN  NaN
1   a1  2.0   c1  NaN  NaN  NaN  NaN
2   a2  3.0   c2   b0   c0   d0   e0
3   a3  4.0   c3   b1   c1   d1   e1
4  NaN  NaN  NaN   b2   c2   d2   e2
5  NaN  NaN  NaN   b3   c3   d3   e3

In [44]:
# DataFrame을 결합할 수 있어요!
# merge()를 이용해서 결합해요! => Database에서 했었던 join

data1 = {
    '학번': [1,2,3,4],
    '이름': ['홍길동','신사임당', '강감찬', '이순신'],
    '학년': [1,3,2,4]
}

data2 = {
    '학번' : [1,2,4,5],
    '학과' : ['철학', '국어국문', '기계', '컴퓨터'],
    '학점' : [3.1, 2.5, 1.6, 4.5]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

display(df1)
display(df2)

# inner join
# result = pd.merge(df1, df2, on='학번', how='inner')
# display(result)

# result = pd.merge(df1, df2, on='학번', how='left')
# result = pd.merge(df1, df2, on='학번', how='right')
result = pd.merge(df1, df2, on='학번', how='outer')
display(result)

   학번    이름  학년
0   1   홍길동   1
1   2  신사임당   3
2   3   강감찬   2
3   4   이순신   4

   학번    학과   학점
0   1    철학  3.1
1   2  국어국문  2.5
2   4    기계  1.6
3   5   컴퓨터  4.5

   학번    이름   학년    학과   학점
0   1   홍길동  1.0    철학  3.1
1   2  신사임당  3.0  국어국문  2.5
2   4   이순신  4.0    기계  1.6
3   5   NaN  NaN   컴퓨터  4.5

In [47]:
data1 = {
    '학번': [1,2,3,4],
    '이름': ['홍길동','신사임당', '강감찬', '이순신'],
    '학년': [1,3,2,4]
}

data2 = {
    '학생학번' : [1,2,4,5],
    '학과' : ['철학', '국어국문', '기계', '컴퓨터'],
    '학점' : [3.1, 2.5, 1.6, 4.5]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# 컬럼명이 다른 경우에 merge해야 하는 경우
result = pd.merge(df1, df2, left_on='학번', right_on='학생학번',
                  how='inner')
display(result)

   학번    이름  학년  학생학번    학과   학점
0   1   홍길동   1     1    철학  3.1
1   2  신사임당   3     2  국어국문  2.5
2   4   이순신   4     4    기계  1.6

In [51]:
data1 = {
    '학번': [1,2,3,4],
    '이름': ['홍길동','신사임당', '강감찬', '이순신'],
    '학년': [1,3,2,4]
}

data2 = {
    '학과' : ['철학', '국어국문', '기계', '컴퓨터'],
    '학점' : [3.1, 2.5, 1.6, 4.5]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2,
                   index=[1,2,4,5])
display(df1,df2)

result = pd.merge(df1,
                  df2,
                  left_on='학번',
                  right_index=True,
                  how='inner')
display(result)

   학번    이름  학년
0   1   홍길동   1
1   2  신사임당   3
2   3   강감찬   2
3   4   이순신   4

     학과   학점
1    철학  3.1
2  국어국문  2.5
4    기계  1.6
5   컴퓨터  4.5

   학번    이름  학년    학과   학점
0   1   홍길동   1    철학  3.1
1   2  신사임당   3  국어국문  2.5
3   4   이순신   4    기계  1.6

In [61]:
# titanic 데이터를 이용해서 함수 mapping과
# grouping하는 내용에 대해서 알아보아요!

import numpy as np
import pandas as pd
import seaborn as sns

# Raw data Loading
titanic = sns.load_dataset('titanic')
# display(titanic)
# print(titanic.shape)
# 모든 행에 대해 age, fare컬럼만 들고 올꺼예요!
df = titanic.loc[:,['age', 'fare']]
display(df.head())

# 사용자 정의 함수를 하나 만들어요!
def add_10(n):
    return n + 10

def add_two_obj(a,b):
    return a + b

# age열의 모든 행에 대해서 함수를 적용해서 10씩 증가.
# Series에 특정 함수를 적용하려면 어떻게 해야 하나요!!
# s1 = df['age'].apply(add_10)
# print(s1)
# s = df['age'].apply(add_two_obj, b=100)
# print(s)
# s = df['age'].apply(lambda x: x + 30)
# print(s)

# Seires말고 DataFrame에 함수를 적용하려면 어떻게 해야 하나요?
# 함수를 다른거 쓰면되요!
# result = df.applymap(add_10)
# display(result)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

<ipython-input-61-41372d643894>:34: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  result = df.applymap(add_10)

      age     fare
0    32.0  17.2500
1    48.0  81.2833
2    36.0  17.9250
3    45.0  63.1000
4    45.0  18.0500
..    ...      ...
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

[891 rows x 2 columns]

In [63]:
# Raw data Loading
titanic = sns.load_dataset('titanic')
# display(titanic)
# print(titanic.shape)
# 모든 행에 대해 age, fare컬럼만 들고 올꺼예요!
df = titanic.loc[:,['age', 'fare']]
display(df.head())

# 정규화(Normalization) - 최대,최소를 이용한 정규화
# MinMaxScaling을 구현해 보아요!

# 사용자 정의 함수
def min_max(s):
    return (s - s.min()) / (s.max() - s.min())

result = df.apply(min_max, axis=0)
display(result)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

          age      fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
886  0.334004  0.025374
887  0.233476  0.058556
888       NaN  0.045771
889  0.321438  0.058556
890  0.396833  0.015127

[891 rows x 2 columns]

In [ ]:
# Series와 DataFrame에 대해서 특정 함수를
# 적용하기위한 방법(apply(), applymap())

In [72]:
# DataFrame의 Grouping

import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
# 필요한 몇개의 컬럼만 추려서 사용할꺼예요!

df = titanic.loc[:,['age', 'sex', 'class', 'fare', 'survived']]
# display(df.head())

grouped = df.groupby('class')
# print(grouped) # 그룹객체가 생성되요!

# for (key, group) in grouped:
#     print(key)
#     display(group)

# 개별 그룹을 가져오는것부터 알아보아요!
group3 = grouped.get_group('Third')
display(group3)

<ipython-input-72-90ae74981fce>:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby('class')

      age     sex  class     fare  survived
0    22.0    male  Third   7.2500         0
2    26.0  female  Third   7.9250         1
4    35.0    male  Third   8.0500         0
5     NaN    male  Third   8.4583         0
7     2.0    male  Third  21.0750         0
..    ...     ...    ...      ...       ...
882  22.0  female  Third  10.5167         0
884  25.0    male  Third   7.0500         0
885  39.0  female  Third  29.1250         0
888   NaN  female  Third  23.4500         0
890  32.0    male  Third   7.7500         0

[491 rows x 5 columns]

In [75]:
# DataFrame의 Grouping

import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
# 필요한 몇개의 컬럼만 추려서 사용할꺼예요!

df = titanic.loc[:,['age', 'sex', 'class', 'fare', 'survived']]
# display(df.head())

# 그룹을 조금 복잡하게 설정할께요!
# 그룹안에 다시 그룹을 만들꺼예요!
grouped = df.groupby(['class', 'sex'])

# for key, group in grouped:
#     print(key)
#     display(group.head(3))

result = grouped.mean()
display(result)

group3 = grouped.get_group(('Third','female'))
display(group3)

<ipython-input-75-6d1f68496dae>:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(['class', 'sex'])

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [83]:
titanic = sns.load_dataset('titanic')
# 필요한 몇개의 컬럼만 추려서 사용할꺼예요!

df = titanic.loc[:,['age', 'sex', 'class', 'fare', 'survived']]
# display(df.head())

grouped = df.groupby('class')
display(grouped.survived.mean())

# age열의 평균값이 30보다 작은 그룹만을 따로 선택.
# 생성된 그룹에 대해 조건을 설정해 조건을 만족하는 그룹만
# 따로 선택하려면 어떻게 해야 하나요
# filter()

group_filter = grouped.filter(lambda x:x.age.mean() < 30)
display(group_filter.tail())

<ipython-input-83-be1f1cbc04e4>:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby('class')

class
First     0.629630
Second    0.472826
Third     0.242363
Name: survived, dtype: float64

      age     sex   class    fare  survived
884  25.0    male   Third   7.050         0
885  39.0  female   Third  29.125         0
886  27.0    male  Second  13.000         0
888   NaN  female   Third  23.450         0
890  32.0    male   Third   7.750         0

In [103]:
import numpy as np
import pandas as pd

mpg_df = pd.read_csv('/content/mpg.csv')

lowest_cty_mpg_manufacturer = mpg_df.groupby('manufacturer')['cty'].mean().idxmin()
display(lowest_cty_mpg_manufacturer)

'lincoln'