In [ ]:
# Web을 통해 Open API를 호출하는 방법에 대해서 알아보았어요!
# 영화진흥위원회 Open API를 호출해서 실행하고 그 결과 JSON을
# 살펴보는것까지 진행!

import numpy as np
import pandas as pd
import json
import urllib

key = '813aae983df0846e2b881e04b0ebec61'
targetDt = '20250101'

movie_url = f'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={key}&targetDt={targetDt}'

load_page = urllib.request.urlopen(movie_url)
# load_page는 response 객체
# 이 객체안에 결과데이터와 헤더정보같은것들이 들어가 있어요!

# print(load_page.read())
# 이렇게 읽어드린 데이터는 JSON(문자열)
# 당연히 문자열은 처리하기 쉽지 않아요. 그래서 객체화 시켜서
# 사용할꺼예요!
json_page = json.loads(load_page.read())
print(type(json_page)) # <class 'dict'>
# print(json_page)

title = json_page['boxOfficeResult']['dailyBoxOfficeList'][0]['movieNm']
print(title)
# 결과 JSON이용해서 DataFrame을 만들고 싶어요!
# 지정 index를 사용할꺼예요. 이 지정 index의 값은 영화순위(rank)
# 컬럼은 3개를 사용할꺼예요.
# 제목, 개봉일, 누적관람객수 <= 이게 컬럼명이예요!
# 이런 DataFrame을 만들어 보세요!

movie_dict = dict() # {}
rank_list = list() # 나중에 rank값으로 index를 설정하기 위해서.
title_list = list() # 제목 리스트
openDt_list = list() # 개봉일 리스트
audiAcc_list = list() # 누적관객수 리스트

for movie in json_page['boxOfficeResult']['dailyBoxOfficeList']:
    rank_list.append(movie['rank'])
    title_list.append(movie['movieNm'])
    openDt_list.append(movie['openDt'])
    audiAcc_list.append(movie['audiAcc'])

movie_dict['제목'] = title_list
movie_dict['개봉일'] = openDt_list
movie_dict['누적관람객수'] = audiAcc_list

df = pd.DataFrame(movie_dict)
df.index = rank_list

display(df)

<class 'dict'>
하얼빈

                        제목         개봉일   누적관람객수
1                      하얼빈  2024-12-24  3095720
2           보고타: 마지막 기회의 땅  2024-12-31   194095
3                      소방관  2024-12-04  3398126
4                   수퍼 소닉3  2025-01-01    97373
5          뽀로로 극장판 바닷속 대모험  2025-01-01    92837
6               무파사: 라이온 킹  2024-12-18   698398
7                    모아나 2  2024-11-27  3408070
8   극장판 짱구는 못말려: 우리들의 공룡일기  2024-12-18   596017
9                      위키드  2024-11-20  2079690
10            시빌 워: 분열의 시대  2024-12-31    40589

In [ ]:
# 많은 경우에 데이터가 Database에 들어가 있어요!
# 데이터 베이스에서 필요한 정보를 추출해서(SQL을 이용)
# DataFrame을 만들어서 사용해 보아요!

# 데이터베이스 : 데이터의 집합체.
# DBMS는 데이터베이스를 사용하기 위한 프로그램의 집합.
# DBMS는 당연히 여러가지가 있어요!(유료, 무료)
# 유료 : Oracle사의 Oracle(상용 DBMS 1등)
#        IBM의 DB2(메인 프레임 1등)
#        MySQL(Oracle이 라이센스를 가져갔어요!)
# 무료 : MySQL을 모태로 만든 MariaDB
#        기타등등 많은 DBMS들이 있어요!

# 우리는 MySQL을 사용할꺼예요!
# MySQL에서 기본적으로 제공하는 클라이언트 툴이 있어요!
# Workbench를 제공하고 이걸 이용해서 사용할 꺼예요!
# 제공된 script파일(.sql)을 이용해서 테이블을 생성하고
# 데이터를 삽입해요!

In [ ]:
# 프로그램적으로 데이터베이스에 접속해서
# SQL을 이용해서 원하는 데이터를 추출한 후에
# 추출한 데이터를 가지고 DataFrame을 생성해 보아요!
# 이거 하려면 추가적인 library가 있어야 해요!
# 우리 작업환경이 Colab환경이예요. 그런데 Colab에서
# 내 로컬컴퓨터안에 있는 Database에 접속해야 해요!
# 당연히 안되요!
# 이 작업을 수행하려면 colab 환경에서는 할 수 없고
# 로컬 anaconda 환경에서 작업해야 할 거 같아요!
# 아나콘다 프롬프트를 실행

In [ ]:
# Database에 접속해서 데이터를 추출한 후에
# DataFrame으로 생성해 보아요!
# 추가적인 library가 필요해요! => sqlalchemy
# base환경에 설치가 이미 되어 있네요! 따로 설치할 필요 없어요!
from sqlalchemy import create_engine, text
import numpy as np
import pandas as pd

# sqlalchemy engine을 생성
# 접속할 수 있는 engine을 생성한 후 connect()를 이용해서 데이터베이스에 접속!
engine = create_engine("mysql+pymysql://root:test1234@localhost:3306/library?charset=utf8mb4")

# 데이터 추출을 위한 SQL
search_keyword = '파이썬'  # 책 제목에 대한 키워드 검색을 하려고 하는거군요!
sql = 'SELECT bisbn, btitle, bauthor, bprice FROM books WHERE btitle LIKE :keyword'

with engine.connect() as connection:
    result = connection.execute(text(sql),
                                {'keyword' : f'%{search_keyword}%'})
    #print(result.fetchone())
    df = pd.DataFrame(result.fetchall())

display(df)

In [ ]:
# pandas의 DataFrame에 대해서 알아보고 있어요!
# DataFrame을 생성할 때 기본적으로는 dict를 이용!
# 추가적으로
# 많은 양의 데이터는 키인을 할 수가 없어요!
# 많은 양의 데이터 같은 경우
# 1. CSV파일을 이용하는 방식 => read_csv()
# 2. Open API를 이용하는 방식 => JSON을 사용
# 3. 데이터베이스 테이블을 이용하는 방식 => 데이터베이스 연결 및 SQL

In [ ]:
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','평균학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)

         학과    이름 평균학점  학년   등급
one     컴퓨터   홍길동  NaN   1  NaN
two    국어국문  신사임당  NaN   2  NaN
three    기계   강감찬  NaN   4  NaN
four    철학과   이순신  NaN   3  NaN
five     물리   정약용  NaN   2  NaN

In [16]:
# 1. 하나의 column을 추출할려면 어떻게 해야 하나요?
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# DataFrame은 여러개의 Series가 모여서 생성된거예요!
# 각각의 Series는 column으로 표현되요!

print(df['이름'])
# DataFrame에 대해 컬럼명으로 indexing을 하면
# 해당 컬럼의 데이터를 Series로 리턴!

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

one       홍길동
two      신사임당
three     강감찬
four      이순신
five      정약용
Name: 이름, dtype: object

In [19]:
# 2. column을 DataFrame에서 추출하면 View로 리턴되요!
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# DataFrame은 여러개의 Series가 모여서 생성된거예요!
# 각각의 Series는 column으로 표현되요!

s = df['이름']
print(s)
s['one'] = '최길동'
print(s)
display(df)

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

one       홍길동
two      신사임당
three     강감찬
four      이순신
five      정약용
Name: 이름, dtype: object
one       최길동
two      신사임당
three     강감찬
four      이순신
five      정약용
Name: 이름, dtype: object

<ipython-input-19-df83700e44cb>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s['one'] = '최길동'

         학과    이름   학점  학년   등급
one     컴퓨터   최길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

In [21]:
# 3. 두 개 이상의 column을 DataFrame에서
#    추출하려면 어떻게 해야 하나요?
# 3-1. 아..~ 컬럼에 대해서 Fancy indexing을 하면되는군요
# 3-2. 앗..그럼 컬럼에 대해서 slicing도 가능한가요?
#      아니요..컬럼에 대한 슬라이싱은 지원하지 않아요
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)

# display(df[['학과', '이름', '학년']])
# display(df['학과':'학점'])

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

KeyError: '학과'

In [27]:
# 4. DataFrame의 특정 컬럼값을 수정할 수 있어요!
#   단 Series를 이용해서 수정할 경우에는 index에 주의해야 해요!
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# df['등급'] = 'A'  # broadcasting을 이용한 값 수정
# df['등급'] = ['A', 'B', 'C', 'D', 'A']
# df['등급'] = np.array(['A', 'B', 'C', 'D', 'A'])
df['등급'] = pd.Series(['A', 'B', 'C', 'D', 'A'],
                     index=['one', 'two', 'three', 'four', 'five'])
display(df)

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

         학과    이름   학점  학년 등급
one     컴퓨터   홍길동  1.5   1  A
two    국어국문  신사임당  4.3   2  B
three    기계   강감찬  2.4   4  C
four    철학과   이순신  3.5   3  D
five     물리   정약용  4.4   2  A

In [30]:
# 5. DataFrame에 없는 컬럼을 새롭게 추가하려면 어떻게 해야 하나요?
#    없는 컬럼에 대한 값을 assign하면 컬럼이 추가되요!
#    단, 컬럼을 추가할 때 데이터의 개수는 맞춰줘야 해요!
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# df['나이'] = [22,23,20,26,29]
df['나이'] = pd.Series([22,23,26,29],
                     index=['one', 'two', 'four', 'five'])
display(df)

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

         학과    이름   학점  학년   등급    나이
one     컴퓨터   홍길동  1.5   1  NaN  22.0
two    국어국문  신사임당  4.3   2  NaN  23.0
three    기계   강감찬  2.4   4  NaN   NaN
four    철학과   이순신  3.5   3  NaN  26.0
five     물리   정약용  4.4   2  NaN  29.0

In [32]:
# 6. DataFrame에 없는 컬럼을 새롭게 추가할 수 있네요!
#    연산을 통한 새로운 컬럼을 생성하는 작업을 많이 활용
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
df['장학여부'] = df['학점'] >= 4.0
display(df)

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

         학과    이름   학점  학년   등급   장학여부
one     컴퓨터   홍길동  1.5   1  NaN  False
two    국어국문  신사임당  4.3   2  NaN   True
three    기계   강감찬  2.4   4  NaN  False
four    철학과   이순신  3.5   3  NaN  False
five     물리   정약용  4.4   2  NaN   True

In [34]:
# 7. DataFrame에 있는 컬럼을 삭제할 수 있어요!
#    삭제는 다른작업과는 다르게 함수를 이용해요! => drop()
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)

new_df = df.drop("등급",
                 axis=1,
                 inplace=False)
display(new_df)

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

         학과    이름   학점  학년
one     컴퓨터   홍길동  1.5   1
two    국어국문  신사임당  4.3   2
three    기계   강감찬  2.4   4
four    철학과   이순신  3.5   3
five     물리   정약용  4.4   2

In [43]:
# 8. DataFrame의 row를 다루는 방법에 대해서 알아보아요!
#    row indexing부터 알아보면 될 거 같아요!
#    loc[]를 이용해서 처리해야 해요!

import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# print(df.loc['one']) # 한개의 행을 loc를 이용해서 가져올 수 있어요!
#                        한개의 행을 가져오면 Series로 만들어져서 리턴.
# 그럼 loc를 이용하면 slicing은 되나요?
# display(df.loc['one':'three']) #  앗..되는군요!
# display(df.loc['three':]) # 이것도 당연히 되요!
# display(df.loc['three':-1]) # 숫자인덱스와 지정인덱스를 함께 사용할 수 없어요!
# display(df.loc[['one', 'three']]) # Fancy indexing 당연히 사용할 수 있어요!
# display(df.loc[0]) # loc는 숫자인덱스를 사용할 수 없어요!
# display(df.iloc[0]) # 숫자인덱스를 사용할 경우 iloc를 사용해야 해요!

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

학과    컴퓨터
이름    홍길동
학점    1.5
학년      1
등급    NaN
Name: one, dtype: object

In [48]:
# 9. loc(iloc)는 행 indexing뿐만 아니라
#                열 indexing도 할 수 있어요!

import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# display(df.loc['one':'three', '이름':'학년'])
# display(df.loc['one':'three', ['이름', '학년']])

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

         이름  학년
one     홍길동   1
two    신사임당   2
three   강감찬   4

In [54]:
# 9. 가장 많이 사용하는 기능 중 하나는
#    당연히 boolean indexing.
import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)

# 학점이 3.0을 초과하는 학생의 이름과 학과를 DataFrame으로 출력!
df.loc[df['학점'] > 3.0, ['이름','학과']]

# 이름이 신사임당인 사람을 찾아서 이름과 학점을 DataFrame으로 출력!
display(df.loc[df['이름'] == '신사임당', '이름':'학점'])

# 학점이 2.0초과 4.0미만인 사람들을 찾아서 학과와 이름을 DF로 출력!
display(df.loc[(df['학점'] > 2.0) & (df['학점'] < 4.0), '학과':'이름'])

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

       이름   학점
two  신사임당  4.3

        학과   이름
three   기계  강감찬
four   철학과  이순신

In [59]:
# 10. row를 추가할 수 있고 삭제할 수 있어요!

import numpy as np
import pandas as pd

data = {
    "이름": ['홍길동', '신사임당', '강감찬', '이순신', '정약용'],
    "학과": ['컴퓨터', '국어국문', '기계', '철학과', '물리'],
    "학년": [1,2,4,3,2],
    "학점": [1.5, 4.3, 2.4, 3.5, 4.4]
}

df = pd.DataFrame(data,
                  columns=['학과','이름','학점','학년','등급'],
                  index=['one', 'two', 'three', 'four', 'five'])
display(df)
# df.loc['six'] = ['체육', '김연아', 4.5, 3, np.nan]
# display(df)

# 삭제는 drop()을 이용해요! 단, axis=0(행방향)으로 지정해야 해요!
new_df = df.drop('three', axis=0, inplace=False)
display(new_df)

         학과    이름   학점  학년   등급
one     컴퓨터   홍길동  1.5   1  NaN
two    국어국문  신사임당  4.3   2  NaN
three    기계   강감찬  2.4   4  NaN
four    철학과   이순신  3.5   3  NaN
five     물리   정약용  4.4   2  NaN

        학과    이름   학점  학년   등급
one    컴퓨터   홍길동  1.5   1  NaN
two   국어국문  신사임당  4.3   2  NaN
four   철학과   이순신  3.5   3  NaN
five    물리   정약용  4.4   2  NaN